# Generated by Django 4.2 on 2023-05-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baseprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='finalprice',
            field=models.FloatField(),
        ),
    ]
