# Generated by Django 4.2 on 2023-05-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baseprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='finalprice',
            field=models.IntegerField(),
        ),
    ]
