# Generated by Django 4.2 on 2023-05-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_buyer_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
