# Generated by Django 4.2 on 2023-05-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_buyer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='username',
        ),
    ]
