# Generated by Django 4.2 on 2023-05-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_orderdetails_orderedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderedproducts',
            name='total',
            field=models.IntegerField(),
        ),
    ]
