# Generated by Django 4.2 on 2023-05-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_rename_orderdetails_orderdetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='final',
            new_name='total',
        ),
    ]
