# Generated by Django 4.2 on 2023-05-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_buyer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='brands'),
        ),
    ]
