# Generated by Django 4.2 on 2023-05-25 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_deliveryaddress_orderdetail_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='deliveryAddress',
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
