# Generated by Django 4.2 on 2023-05-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_remove_orderdetail_deliveryaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='rppid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
